// SPDX-License-Identifier: GPL-3.0
// Copyright (c) 2025 Schubert Anselme <schubert@anselm.es>

/**
 @file BridgingHeader.h
 @brief Bridging Header for Swift-Zephyr RTOS Interoperability

 This header serves as the primary bridging interface between Swift and C code
 in the ZephyrSys project. It includes necessary Zephyr RTOS headers to make
 Zephyr functionality available to Swift code through C interoperability.

 ## Swift 6.3 Integration

 With Swift 6.3's enhanced C interoperability features, this header enables:
 - Bidirectional Swift-C function calls
 - Improved tolerance of C signature mismatches
 - Support for @c @implementation attribute
 - Enhanced embedded Swift runtime compatibility

 ## Header Organization

 Headers are organized into logical groups:
 - Project configuration: Generated by Zephyr build system (Kconfig)
 - Kernel APIs: Core Zephyr kernel functionality
 - Device APIs: Hardware access and management
 - ZephyrSys Interface: C functions implemented in Swift

 ## Usage

 This header is processed when:
 - Swift compiler uses the '-import-bridging-header' flag
 - C code includes this header for ZephyrSys functions
 - CMake build system processes Swift-C interoperability

 @see main.swift For Swift implementations of C functions
 @see module.modulemap For Clang module definitions
 */

#pragma once

// ===== Project Configuration =====

// Include auto-generated configuration header
// This file is generated by Kconfig during the build process and contains
// all the project configuration settings from prj.conf
#include <autoconf.h>

// Standard C library headers
#include <errno.h>

// ===== Zephyr Kernel APIs =====

// Core kernel functionality including scheduling, threading, and
// synchronization
#include <zephyr/kernel.h>

// Random number generation APIs
#include <zephyr/random/random.h>

// ===== Device and Hardware APIs =====

#include <zephyr/device.h>        // Generic device model interfaces for hardware access
#include <zephyr/drivers/gpio.h>  // GPIO interfaces for pin control and interrupts

// ===== ZephyrSys C Interface Declarations =====

/**
 @brief C interface declarations for functions implemented in Swift

 These declarations define the C interface that Swift code implements
 using the @c @implementation attribute. The Swift compiler verifies
 that Swift implementations match these exact signatures, ensuring
 type safety and C ABI compatibility.

 ## Swift 6.3 Implementation

 Functions declared here are implemented in main.swift using:
 - @c @implementation for existing C interface compatibility
 - @c("function_name") for custom C symbol names
 - Embedded Swift features for minimal runtime overhead

 ## Usage from C

 C code can call these functions directly:
 ```c
 #include "BridgingHeader.h"

 int main() {
    zephyr_sys_init();  // Implemented in Swift
    return 0;
 }
 ```

 ## Usage from Swift

 Swift code can also call these functions:
 ```swift
 import ZephyrSys

 zephyr_sys_init()  // Calls Swift implementation
 ```
 */

#ifdef __cplusplus
extern "C" {
#endif

/**
 @brief Initialize ZephyrSys runtime support (implemented in Swift)

 Initializes the ZephyrSys library and any required runtime components.
 This function is implemented in Swift using @c @implementation attribute.
 */
void zephyr_sys_init(void);

// Additional C interface functions can be declared here and implemented in Swift
// Uncomment and implement as needed:
//
// /** @brief Get ZephyrSys library version (Swift implementation) */
// const char* zephyr_sys_get_version(void);
//
// /** @brief Check if ZephyrSys is initialized (Swift implementation) */
// int zephyr_sys_is_initialized(void);
//
// /** @brief Aligned memory allocation stub (Swift implementation) */
// void* aligned_alloc(size_t alignment, size_t size);
//
// /** @brief POSIX aligned memory allocation stub (Swift implementation) */
// int posix_memalign(void **memptr, size_t alignment, size_t size);
//
// /** @brief Entropy generation stub (Swift implementation) */
// int getentropy(void *buf, size_t buflen);

#ifdef __cplusplus
}
#endif
