// SPDX-License-Identifier: GPL-3.0
// Copyright (c) 2025 Schubert Anselme <schubert@anselm.es>

/**
 * @file BridgingHeader.h
 * @brief Common header for Zephyr and Embedded Swift integration.
 *
 * This header serves as the bridging interface between Swift and C code in the
 * project. It includes necessary Zephyr RTOS headers to make Zephyr
 * functionality available to Swift code through C interoperability. The Swift
 * compiler processes this header when the '-import-bridging-header' flag is
 * used during compilation.
 *
 * Headers are organized into logical groups:
 * - Project configuration: Generated by Zephyr build system
 * - Kernel APIs: Core Zephyr kernel functionality
 * - Device APIs: Hardware access and management
 * - GPIO APIs: General purpose I/O control
 */

#pragma once

// ===== Project Configuration =====

// Include auto-generated configuration header
// This file is generated by Kconfig during the build process and contains
// all the project configuration settings from prj.conf
#include <autoconf.h>

// ===== Zephyr Kernel APIs =====

// Core kernel functionality including scheduling, threading, and
// synchronization
#include <zephyr/kernel.h>

// ===== Device and Hardware APIs =====

#include <zephyr/device.h> // Generic device model interfaces for hardware access
#include <zephyr/drivers/gpio.h> // GPIO interfaces for pin control and interrupts
