// SPDX-License-Identifier: GPL-3.0
// Copyright (c) 2025 Schubert Anselme <schubert@anselm.es>

#pragma once

// ===== Project Configuration =====

// Include auto-generated configuration header
// This file is generated by Kconfig during the build process and contains
// all the project configuration settings from prj.conf
#include <autoconf.h>

// Standard C library headers
#include <errno.h>

// ===== Zephyr Kernel APIs =====

// Core kernel functionality including scheduling, threading, and
// synchronization
#include <zephyr/kernel.h>

// Random number generation APIs
#include <zephyr/random/random.h>

// ===== Device and Hardware APIs =====

#include <zephyr/device.h>        // Generic device model interfaces for hardware access
#include <zephyr/drivers/gpio.h>  // GPIO interfaces for pin control and interrupts

// ===== ZephyrSys C Interface Declarations =====

void zephyr_sys_init(void);
// const char* zephyr_sys_get_version(void);
// int zephyr_sys_is_initialized(void);
// void* aligned_alloc(size_t alignment, size_t size);
// int posix_memalign(void **memptr, size_t alignment, size_t size);
// int getentropy(void *buf, size_t buflen);
