name: Continuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  bot:
    uses: anselmes/cicd/.github/workflows/bot.yml@96ca47c59a516ea9022fbe449889c64e7d4ea3fe # v0.2.3
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write

  trivy:
    uses: anselmes/cicd/.github/workflows/trivy.yml@96ca47c59a516ea9022fbe449889c64e7d4ea3fe # v0.2.3
    permissions:
      contents: write
      id-token: write
      security-events: write

  scorecard:
    uses: anselmes/cicd/.github/workflows/scorecard.yml@96ca47c59a516ea9022fbe449889c64e7d4ea3fe # v0.2.3
    permissions:
      contents: read
      id-token: write
      security-events: write
