name: Continuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  bot:
    uses: anselmes/cicd/.github/workflows/bot.yml@3cca70a2245ec4bedf469088b3c21cbb77dfee2f # v0.2.2
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write

  trivy:
    uses: anselmes/cicd/.github/workflows/trivy.yml@3cca70a2245ec4bedf469088b3c21cbb77dfee2f # v0.2.2
    permissions:
      contents: write
      id-token: write
      security-events: write

  scorecard:
    uses: anselmes/cicd/.github/workflows/scorecard.yml@3cca70a2245ec4bedf469088b3c21cbb77dfee2f # v0.2.2
    permissions:
      contents: read
      id-token: write
      security-events: write
