name: Continuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  bot:
    uses: anselmes/cicd/.github/workflows/bot.yml@042c5469e6121d8aa7578e177c58e12deebff9e1 # v0.2.1
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write

  trivy:
    uses: anselmes/cicd/.github/workflows/trivy.yml@042c5469e6121d8aa7578e177c58e12deebff9e1 # v0.2.1
    permissions:
      contents: write
      id-token: write
      security-events: write

  scorecard:
    uses: anselmes/cicd/.github/workflows/scorecard.yml@042c5469e6121d8aa7578e177c58e12deebff9e1 # v0.2.1
    permissions:
      contents: read
      id-token: write
      security-events: write
